### ISSUE TITLE
[Bug]: Authentication header included, but incorrectly formatted.

### ISSUE THREAD

**Issue by 17Amir17** [PaddleHQ/paddle-node-sdk#39]
### What happened?

Cannot get customers with Paddle API

```ts
import { Paddle } from "@paddle/paddle-node-sdk";
import { PADDLE_API_KEY_NAME } from "./env-utils";

export const paddle = new Paddle(PADDLE_API_KEY_NAME);
await paddle.customers.get(customerID); // <--- Error thrown here
```

### Steps to reproduce

1. Copy code in issue
2. Add keys
3. Get customer
...

### Logs

```shell
NEW EVENT:  subscription.created
[Paddle] [LOG] [Request] GET https://api.paddle.com/customers/ctm_01j5wzhv36kpwzf3peg8x6vn5y Transaction ID: 5c647324-be3e-4a2c-bf5d-b1850acc1af9
[Paddle] [LOG] [Response] GET https://api.paddle.com/customers/ctm_01j5wzhv36kpwzf3peg8x6vn5y 403 Transaction ID: 5c647324-be3e-4a2c-bf5d-b1850acc1af9 Request ID: null
ApiError: Authentication header included, but incorrectly formatted.
    at CustomersResource.handleError (/var/task/node_modules/@paddle/paddle-node-sdk/dist/cjs/internal/base/base-resource.js:11:19)
    at CustomersResource.handleResponse (/var/task/node_modules/@paddle/paddle-node-sdk/dist/cjs/internal/base/base-resource.js:17:14)
    at CustomersResource.<anonymous> (/var/task/node_modules/@paddle/paddle-node-sdk/dist/cjs/resources/customers/index.js:55:31)
    at Generator.next (<anonymous>)
    at fulfilled (/var/task/node_modules/@paddle/paddle-node-sdk/dist/cjs/resources/customers/index.js:19:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'request_error',
  code: 'authentication_malformed',
  detail: 'Authentication header included, but incorrectly formatted.',
  documentationUrl: 'https://developer.paddle.com/v1/errors/shared/authentication_malformed',
  errors: null
}
```

**Comment by vijayasingam-paddle** [comment]
Hi @17Amir17, 
Thank you for raising this issue to us. 

Looking at the error message, I think you are passing an incorrect API key under the variable `PADDLE_API_KEY_NAME`. 

Can you please double check if you are passing the correct API key from the `API Keys` section in the [authentication page](https://vendors.paddle.com/authentication-v2). 

Thank you.

**Comment by 17Amir17** [comment]
Yes, I took the key from `API keys` section (also tried creating a new one and using that) 
Also I pass the key name and the value, is this correct?

**Comment by vijayasingam-paddle** [comment]
Hello 👋 , 
Sorry, no.. you should only be passing in the API key, we do not need the name of the key.

For example, 
`export const paddle = new Paddle(1234);  // where 1234 is the API key`

**Comment by 17Amir17** [comment]
Oh ok got it, thanks!
